server {
    listen <SERVER_IP>:8889;

    server_name _;
    root /opt/oxidized-web/public;
    index index.php;

    charset utf-8;
    gzip on;
    gzip_types text/css application/javascript application/json text/plain;

    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options SAMEORIGIN always;
    add_header Referrer-Policy no-referrer always;

    access_log /var/log/nginx/oxidized-web.access.log;
    error_log /var/log/nginx/oxidized-web.error.log;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ [^/]\.php(/|$) {
        fastcgi_pass unix:/run/php-fpm-oxidized.sock;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        include fastcgi.conf;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~ /\.(?!well-known).* { deny all; }
}